## Put comments here that give an overall description of what your
## functions do
## This file comprises of 2 functions
## 1) makeCacheMatrix - generates a list of functions from a matrix
## 2) cacheSolve - uses the list of functions generated by MakeCacheMatrix to 
##   calculate and cache the original matrix's inverse

## Write a short comment describing this function
## 'The function'makeCacheMatrix' effectively creates a list of 
## 4 functions from a matrix. 
## 'set' stores a matrix, 'get' retrieves that stored matrix
## 'setinverse' store an inverse of a matrix,
## 'getinverse' returns the stored matrix
makeCacheMatrix <- function(x = matrix()) {
  
  inverse <- NULL
  set <- function(y) {
    x <<- y
    inverse <<- NULL
  }
  get <- function() x
  setinverse <- function(solve) inverse <<- solve
  getinverse <- function() inverse
  list(set = set, get = get,
       setinverse = setinverse,
       getinverse = getinverse)
}


## Write a short comment describing this function
## This function uses the list of functions created by  passing a matrix into
## 'MakeCacheMatrix'.
## getinverse is used to determine if an inverse has been calculated
## if not, then the inverse is calculated and cached by 'setinverse'
## subsequent requests for the inverse are serviced with the 'getinverse' function

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  
  m <- x$getinverse()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setinverse(m)
  m
  
}
